-- create tables
CREATE TABLE MANAGER_TABLE (
    MANAGER_ID NUMBER(9) NOT NULL,
    FIRSTNAME VARCHAR2(50),
    LASTNAME VARCHAR2(50),
    MANAGER_USERNAME VARCHAR2(50) NOT NULL,
    MANAGER_PASSWORD VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_MANAGER PRIMARY KEY (MANAGER_ID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER(9) NOT NULL,
    FIRSTNAME VARCHAR2(50),
    LASTNAME VARCHAR2(50),
    EMPLOYEE_USERNAME VARCHAR2(50) NOT NULL,
    EMPLOYEE_PASSWORD VARCHAR2(50) NOT NULL,
    REPORTSTO NUMBER(9) NOT NULL,
    ADDRESS VARCHAR2(90),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE REQUEST (
    REQUEST_ID NUMBER(9) NOT NULL,
    TYPE1 VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(8),
    DECISION VARCHAR2(8),
    AMOUNT NUMBER(9,2) NOT NULL,
    EMPLOYEE_ID NUMBER(9) NOT NULL,
    MANAGER_ID NUMBER(9),
    CONSTRAINT PK_REQUEST PRIMARY KEY (REQUEST_ID)
);

-- create foreign keys
ALTER TABLE REQUEST
ADD CONSTRAINT FK_MANAGER_ID
FOREIGN KEY (MANAGER_ID) 
REFERENCES MANAGER_TABLE (MANAGER_ID)
ON DELETE CASCADE;

ALTER TABLE REQUEST
ADD CONSTRAINT FK_EMPLOYEE_ID
FOREIGN KEY (EMPLOYEE_ID) 
REFERENCES EMPLOYEE (EMPLOYEE_ID)
ON DELETE CASCADE;

-- populate employee table
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (1, 'Maribel', 'Friedenbach', 'mfriedenbach0', 'PxRrdE1QCGiH', 1, '190 Eliot Drive');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (2, 'Filippa', 'Phelan', 'fphelan1', 'MQwArNI7AAAu', 2, '8922 Dexter Lane');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (3, 'Ellyn', 'Edworthie', 'eedworthie2', 'w2mYKSpjmD', 3, '71033 Kennedy Junction');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (4, 'Maryjane', 'Romeuf', 'mromeuf3', 'z6FyVb', 4, '2 Marquette Way');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (5, 'Nikolaos', 'Shortan', 'nshortan4', 'WFtkc4NSb', 5, '0 Waubesa Street');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (6, 'Eden', 'Dugood', 'edugood5', 'wa5T13', 6, '314 Cody Hill');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (7, 'Myrtle', 'Abyss', 'mabyss6', 'RPKqlg3I', 7, '4 Buhler Terrace');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (8, 'Kaitlin', 'Ferraraccio', 'kferraraccio7', 'tupx0i92a3il', 8, '6 Ronald Regan Avenue');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (9, 'Maryjo', 'Platt', 'mplatt8', 'O4TQmGdgIPl1', 9, '312 Mallory Trail');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (10, 'Andree', 'McKern', 'amckern9', 'Y0YjftQiZBzl', 10, '1668 Nelson Park');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (11, 'Lacee', 'Dunnet', 'ldunneta', 'CiDxPgpENDHH', 3, '58 Atwood Court');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (12, 'Ellette', 'Clunie', 'eclunieb', 'gdHXKA6', 1, '1 Pepper Wood Junction');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (13, 'Keenan', 'Bourton', 'kbourtonc', 'I9d5jx3vvMc', 2, '1840 Utah Circle');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (14, 'Dorothee', 'Krier', 'dkrierd', '9FigDM97AC', 4, '7566 Grover Trail');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (15, 'Leah', 'Cloke', 'lclokee', 'srFWrG', 7, '172 Oneill Point');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (16, 'Demetria', 'Keuntje', 'dkeuntjef', 'YoblCPT0BQl', 9, '0 Grover Alley');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (17, 'Vaughan', 'Gilluley', 'vgilluleyg', 'nkY5mqVykXjD', 6, '88 Bunker Hill Circle');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (18, 'Doretta', 'Cheverell', 'dcheverellh', 'fZUTi0fUTk8x', 7, '9 Esch Drive');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (19, 'Ajay', 'Doram', 'adorami', 'DyJug8fRDH', 5, '3878 Continental Way');
insert into EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, REPORTSTO, ADDRESS) values (20, 'Dat', 'Tran', 'dtran', 'pass123', 10, '4665 Burning Wood Place');


-- populate manager table
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (1, 'Orlan', 'Ellinor', 'oellinor0', 'GiZ7ajmTTeY1');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (2, 'Clerissa', 'Mohamed', 'cmohamed1', '7SjNmU');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (3, 'Oates', 'Gierhard', 'ogierhard2', '5t08Pzs');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (4, 'Marney', 'Bigley', 'mbigley3', 'PwrIUPzOX');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (5, 'Siward', 'Booy', 'sbooy4', 'wmRGq308lE');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (6, 'Robbert', 'Millership', 'rmillership5', '0Y12rnZ');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (7, 'Gayleen', 'Schrei', 'gschrei6', 'Jvr3mdMpUb');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (8, 'Corena', 'Rodmell', 'crodmell7', '3IiOtk');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (9, 'Karyl', 'Dennerley', 'kdennerley8', 'oA5bVGkuBIB');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (10, 'Carol', 'Dainor', 'knferas', '8s2hsdf8');
insert into MANAGER_TABLE (MANAGER_ID, FIRSTNAME, LASTNAME, MANAGER_USERNAME, MANAGER_PASSWORD) values (11, 'Vu', 'Bui', 'v', 'v');

-- populate request table


COMMIT;

--SELECT * FROM EMPLOYEE;
--SELECT * FROM REQUEST WHERE STATUS != 'pending';

--SELECT * FROM REQUEST
--WHERE EMPLOYEE_ID = 2;

--SELECT E.EMPLOYEE_ID, E.FIRSTNAME, E.LASTNAME, M.FIRSTNAME, M.LASTNAME
--FROM EMPLOYEE E
--INNER JOIN MANAGER_TABLE M ON E.REPORTSTO = M.MANAGER_ID

